import uuid
from datetime import datetime
from sqlalchemy import (
    Column,
    String,
    Float,
    Boolean,
    DateTime,
    ForeignKey,
    Date,
    JSON,
    Text,
)
from sqlalchemy import Uuid as UUID
from app.models.user import Base


class KPIMetric(Base):
    """
    Materialized View / Pre-aggregated data table.
    Populated nightly or hourly by a Celery background job.
    """

    __tablename__ = "kpi_metrics"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    org_id = Column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
    )
    date_recorded = Column(Date, nullable=False)

    metric_name = Column(
        String(100), nullable=False
    )  # e.g., 'total_revenue', 'new_leads', 'ai_tokens'
    metric_value = Column(Float, nullable=False)
    dimension = Column(String(100))  # e.g., 'region_na', 'product_saas'

    created_at = Column(DateTime, default=datetime.utcnow)


class DashboardWidget(Base):
    """
    User customizable dashboard layouts.
    """

    __tablename__ = "dashboard_widgets"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    dashboard_type = Column(String(50), default="executive")  # executive, sales, ai
    widget_type = Column(String(50), nullable=False)  # line_chart, kpi_card, funnel
    data_source = Column(String(100), nullable=False)  # e.g., 'revenue_over_time'
    layout_config = Column(JSON, default=dict)  # x, y, w, h for drag-and-drop

    created_at = Column(DateTime, default=datetime.utcnow)


class AIInsight(Base):
    """
    Predictive alerts generated by the LLM based on KPI anomalies.
    """

    __tablename__ = "ai_insights"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    org_id = Column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
    )
    insight_type = Column(
        String(50), nullable=False
    )  # revenue_risk, churn_risk, opportunity
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=False)
    confidence_score = Column(Float)
    is_actioned = Column(Boolean, default=False)

    created_at = Column(DateTime, default=datetime.utcnow)
